# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'RealmResultsController' do
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
end

target 'RealmResultsControllerTests' do
  pod 'Quick', '~> 0.5.0'
  pod 'Nimble', '2.0.0-rc.2'
end

